### ISSUE TITLE
Replace parameters in the config.url string

### ISSUE THREAD

**Issue by biancarosa** [stone-payments/kong-plugin-url-rewrite#15]
### Issue Description
We should replace the `config.url` with the same parameters that the `template-transformer` receives: https://github.com/stone-payments/kong-plugin-template-transformer/blob/master/template-transformer/handler.lua#L74.

We can replace with common regex or use the resty_template lib as in the `template-transformer` plugin.       

### Expected Behavior

We should be able to use paramets in the custom urls.

### Checklist

- [x] Tests
- [x] Linter ok
- [x] Decent coverage

**Comment by PFadel** [comment]
Solved by https://github.com/stone-payments/kong-plugin-url-rewrite/pull/18
