### ISSUE TITLE
Rewrite dynamic part of URL

### ISSUE THREAD

**Issue by TamerElfeky** [stone-payments/kong-plugin-url-rewrite#21]
### Issue Description
I have an exposed API like : 
http://examlpe.com/v2/cart/<dymaic_part>  and need to map it to 
http://examlpe.com/api/cart/<dymaic_part>

Configuration :
  "config": {
    "url": "/api/cart/"
  },

i got all requests mapped to http://examlpe.com/api/cart/ without the dynamic part.

**Comment by PFadel** [comment]
Hello @TamerElfeky , you can use [kong regex proxy](https://docs.konghq.com/0.14.x/proxy/#using-regexes-in-paths) to create something like this:

**Your route path  in Kong**: `/v2/cart/(?<dymaic_part>\\S+)`

And then in the **plugin configuration**: `"url": "/api/cart/<dymaic_part>"`

Hope this helps!

**Comment by PFadel** [comment]
Closing this for lack of response and I believe it was answered.

**Comment by kaleocheng** [comment]
you need to use  `/v2/cart/(?<dymaic_part>\S+)` instead of `/v2/cart/(?<dymaic_part>\\S+)` for kong 1.x
