### ISSUE TITLE
with recent kong host can not be changed, only path?

### ISSUE THREAD

**Issue by javapowered** [stone-payments/kong-plugin-url-rewrite#22]
### Issue Description

I'm using kong 1.0.3
When I've tried to use this from readme:

curl -X POST http://localhost:8001/routes/{routeId}/plugins --data "name=kong-plugin-url-rewrite" --data "config.url=http://new-url.com"

I receive Internal server error 500 when I try load corresponding page.
And I have this in kong's error.log:
invalid port in upstream "kong_upstreamhttp://new-url.com"

Instead I tried this:

curl -X POST http://localhost:8001/routes/{routeId}/plugins --data "name=kong-plugin-url-rewrite" --data "config.url=/new/url"

and it works
Seems host can not be updated, only path, as discussed here https://github.com/Kong/kong/issues/2834

If I am correct may be readme have to be updated.
### Checklist

**Comment by PFadel** [comment]
Hello @javapowered ! 

First thanks for the report, but you can see in [our hub page](https://docs.konghq.com/hub/stone-payments/kong-plugin-url-rewrite/) that we don't have compatibility with kong 1.0.x yet. This is something we want to do but haven't got the time yet, if you want to feel free to suggest a pull request!

**Comment by PFadel** [comment]
Closing this for lack of response and I believe it was answered.
