### ISSUE TITLE
Can't Rewrite Dynamic requests

### ISSUE THREAD

**Issue by davideagle** [stone-payments/kong-plugin-url-rewrite#23]
### Issue Description

I have a path/route /api/user/v1/isGoldMember/ and I'm using your plugin to rewrite it to /v1/isGoldMember/ on the upstream.

when I request api.foo.bar/api/user/v1/isGoldMember/{user}/ the request hitting my upstream is /v1/isGoldMember/ but not /v1/isGoldMember/{user}/

### Expected Behavior

Well this here  a bow might be the expected behaviour but what I was expecting was the rewritten url to include what comes after the /api/user/v1/isGoldMember/,  ({user}) in the request to the upstream

**Comment by PFadel** [comment]
Hey @davideagle , you could do this by describing your route path like this:

`/api/user/v1/isGoldMember/(?<user>\\S+)`

And then setting the plugin rewrite configuration to:

`/v1/isGoldMember/<user>`

**Comment by davideagle** [comment]
@PFadel, thanks for the response,  I'm using kong ingress controller in Kubernetes and the Ingress definition where you define the route/path throws spec.rules[0].http.paths[0].path: Invalid value: "/api/user/v1/isGoldMember/(?<user>\\S+)": must be a valid regex

Any Idea how I'd solve this ?

**Comment by PFadel** [comment]
@davideagle I believe you need to give a name for the captured group.

does `/api/user/v1/isGoldMember/(?<user>\\S+)` throw the same error ?

You can see how Kong works with this right [here](https://docs.konghq.com/1.1.x/proxy/#capturing-groups).

**Comment by PFadel** [comment]
Closing this for lack of response.
